### ISSUE TITLE
I need your guidance

### ISSUE THREAD

**Issue by khomohzie** [Muzzamil1/ethereum-solidity-course-updated-code-typescript#1]
Hello, I really appreciate the work you have done with refactoring this course projects source codes.

However, there are quite some things I'll like you to explain.

I will be very grateful if there is a way I can contact you for your mentorship.

Thank you @Muzzamil1

**Comment by Muzzamil1** [comment]
Hi, @khomohzie sorry for the late reply. I was busy over the past few days.

How can I help?
